/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as QSlugRouteImport } from './routes/q.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicSaleRouteImport } from './routes/api/public/sale'
import { Route as AuthenticatedAdminQuizIdRouteImport } from './routes/_authenticated/admin/quiz.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const QSlugRoute = QSlugRouteImport.update({
  id: '/q/$slug',
  path: '/q/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSaleRoute = ApiPublicSaleRouteImport.update({
  id: '/api/public/sale',
  path: '/api/public/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminQuizIdRoute =
  AuthenticatedAdminQuizIdRouteImport.update({
    id: '/admin/quiz/$id',
    path: '/admin/quiz/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/q/$slug': typeof QSlugRoute
  '/api/public/sale': typeof ApiPublicSaleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/quiz/$id': typeof AuthenticatedAdminQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/q/$slug': typeof QSlugRoute
  '/api/public/sale': typeof ApiPublicSaleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/quiz/$id': typeof AuthenticatedAdminQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/q/$slug': typeof QSlugRoute
  '/api/public/sale': typeof ApiPublicSaleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/quiz/$id': typeof AuthenticatedAdminQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/q/$slug'
    | '/api/public/sale'
    | '/admin/'
    | '/admin/quiz/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/q/$slug'
    | '/api/public/sale'
    | '/admin'
    | '/admin/quiz/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/q/$slug'
    | '/api/public/sale'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/quiz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  QSlugRoute: typeof QSlugRoute
  ApiPublicSaleRoute: typeof ApiPublicSaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$slug': {
      id: '/q/$slug'
      path: '/q/$slug'
      fullPath: '/q/$slug'
      preLoaderRoute: typeof QSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sale': {
      id: '/api/public/sale'
      path: '/api/public/sale'
      fullPath: '/api/public/sale'
      preLoaderRoute: typeof ApiPublicSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/quiz/$id': {
      id: '/_authenticated/admin/quiz/$id'
      path: '/admin/quiz/$id'
      fullPath: '/admin/quiz/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminQuizIdRoute: typeof AuthenticatedAdminQuizIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminQuizIdRoute: AuthenticatedAdminQuizIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  QSlugRoute: QSlugRoute,
  ApiPublicSaleRoute: ApiPublicSaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
